import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import { garamond, oldStandard } from "./fonts";
import Footer from "@/components/footer";
import SettingsButton from "@/components/settings-button";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${garamond.variable} ${oldStandard.variable} antialiased`}
      >
        <ThemeProvider>
          <Nav />
          {children}
          <Footer />
          <SettingsButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
